cozy/mespapiers

- .travis.yml
Remove useless `matrix` and add `MATTERMOST_CHANNEL` variable
> fix: Configuration Travis

- src/components/Contexts/DialogModalProvider.jsx
- src/components/Contexts/index.jsx
- src/components/Home/Home.jsx
- src/components/ImportDropdown/ImportDropdown.jsx
- src/components/Placeholders/Placeholder.jsx
- src/components/Stepper/Stepper.jsx
- src/components/Stepper/index.jsx
- src/constants/papersDefinitions.json
- src/locales/en.json
- src/locales/fr.json
- src/targets/browser/index.jsx
- test/components/AppLike.jsx
Ajout d'un Stepper pour piloter de futurs modales type `Dialog`
L'idée est d'avoir une modale type `Dialog` par Step
> feat: Add Stepper & DialogModalProvider

- package.json
- yarn.lock
Mise à jour du package `cozy-scripts` suite à la mise jour de `cozy-stack` (`cozy.tools` => `cozy.localhost`)
cf: https://github.com/cozy/create-cozy-app/pull/1402
> fix(deps): Update cozy-scripts

- src/components/StepperDialog/StepperDialog.jsx
- src/components/StepperDialogWrapper/StepperDialogWrapper.jsx
Ajout de la prop `stepper` à la `StepperDialog` afin d'afficher ce dernier.
> feat: Add stepper info to StepperDialog

- src/components/App.jsx
- src/components/CompositeHeader/index.jsx
- src/components/Contexts/index.jsx
- src/components/Home/Home.jsx
- src/components/Home/Home.spec.jsx
- src/components/Home/index.jsx
- src/components/HomeWrapper/HomeWrapper.jsx
- src/components/HomeWrapper/index.jsx
- src/components/Hooks/index.jsx
- src/components/Hooks/useStepperDialogContext.jsx
- src/components/ImportDropdown/ImportDropdown.jsx
- src/components/ImportDropdown/ImportDropdown.spec.jsx
- src/components/ImportDropdown/index.jsx
- src/components/LazyLoad/LazyLoad.jsx
- src/components/LazyLoad/index.jsx
- src/components/Papers/PapersList.jsx
- src/components/Papers/index.jsx
- src/components/Placeholders/Placeholder.jsx
- src/components/Placeholders/Placeholder.spec.jsx
- src/components/Placeholders/PlaceholdersList.jsx
- src/components/Placeholders/PlaceholdersList.spec.jsx
- src/components/Placeholders/index.jsx
- src/components/StepperDialog/index.jsx
- src/components/StepperDialogWrapper/StepperDialogWrapper.jsx
- src/components/StepperDialogWrapper/index.jsx
- src/targets/browser/index.jsx
- test/components/AppLike.jsx
Suppression des tous les fichiers `index` qui faisaient uniquement du ré-export de fichiers.
> feat: Remove all re-export index files

- package.json
- src/components/App.jsx
- src/components/Viewer/FileViewerWithQuery.jsx
- src/components/Viewer/FilesViewer.jsx
- src/components/Viewer/Footer/BottomSheetContent.jsx
- src/components/Viewer/Footer/BottomSheetWrapper.jsx
- src/components/Viewer/Footer/DownloadButton.jsx
- src/components/Viewer/Footer/FooterContent.jsx
- src/components/Viewer/Footer/ForwardButton.jsx
- src/components/Viewer/Footer/Sharing.jsx
- src/components/Viewer/Panel/Certifications.jsx
- src/components/Viewer/Panel/PanelContent.jsx
- src/components/Viewer/Panel/getPanelBlocks.jsx
- src/components/Viewer/helpers.js
- src/components/Viewer/locales/en.json
- src/components/Viewer/locales/fr.json
- src/components/Viewer/queries.js
- src/utils/queries.js
- yarn.lock
- Ajout du composant `FilesViewer` qui retournera l'`Overlay` et le `Viewer` de `cozy-ui`
- Ajout des composants `FooterContent` & `PanelContent` (et leurs enfants)
- Ajout du package `cozy-sharing` nécessaire au composant ci-dessus
> feat: Add FileViewer component

- package.json
- src/components/Home/Home.jsx
- yarn.lock
Mise à jour de cozy-ui pour profiter de l'évolution du composant `Empty`
> Feat/update cozy UI

- src/components/App.jsx
- src/components/Home/Home.jsx
- src/components/HomeWrapper/HomeWrapper.jsx
- src/components/Papers/PaperGroup.jsx
- src/components/Papers/PaperLine.jsx
- src/components/Papers/PapersList.jsx
- src/components/Placeholders/PlaceholdersList.jsx
- src/components/Viewer/FileViewerWithQuery.jsx
- src/utils/queries.js
- test/jestLib/setup.js
Ajout du composant qui liste les labels des qualifications des fichiers comme lien pour accéder aux listes des fichiers correspondants.
> feat: Add PaperGroup component

- package.json
- yarn.lock
~~Waiting until https://github.com/cozy/mespapiers/pull/47 is merged~~
Ready for Review 📓
> feat: Upgrade cozy-client package

- src/components/Contexts/FormDataProvider.jsx
- src/components/Home/Home.jsx
- src/components/Home/Home.spec.jsx
- src/components/HomeWrapper/HomeWrapper.jsx
- src/components/HomeWrapper/HomeWrapper.spec.jsx
- src/components/ModelSteps/AcquisitionResult.jsx
- src/components/ModelSteps/widgets/ContactAdapter.jsx
- src/components/Papers/PaperLine.jsx
- src/locales/en.json
- src/locales/fr.json
- src/utils/fetchCurrentUser.js
- src/utils/fetchCurrentUser.spec.js
- src/utils/getFolderWithReference.js
- src/utils/getFolderWithReference.spec.js
- src/utils/queries.js
Sauvegarde d'un Papier, avec sa qualification enrichie
> feat: Saving a paper

- CHANGELOG.md
- src/components/Contexts/StepperDialogProvider.jsx
- src/components/ModelSteps/Contact.jsx
- src/locales/en.json
- src/locales/fr.json
Add a button to generate documents and simulate the selection of its own contact.
> feat: Add validation button on Contact step

- src/components/Home/Home.spec.jsx
- src/components/HomeWrapper/HomeWrapper.spec.jsx
- src/components/ImportDropdown/ImportDropdown.spec.jsx
- src/components/Papers/PaperLine.spec.jsx
- src/components/Papers/PapersList.spec.jsx
- src/components/Placeholders/Placeholder.spec.jsx
- src/components/Placeholders/PlaceholdersList.spec.jsx
- test/components/AppLike.jsx
- test/jestLib/setup.js
Moved Mock of `cozy-scanner` in `AppLike` to avoid repetition and having to Mock it in components that do not use it directly
> chore: Clean tests

- src/components/HomeWrapper/HomeWrapper.jsx
We can have more than 100 papers. So let's call the fetchMore method if needed :) 
@Merkur39 it works as expected :)
> fix: Call fetchMore

- src/components/App.jsx
- src/components/HomeWrapper/HomeWrapper.jsx
- src/components/ImportDropdown/ImportDropdown.jsx
- src/components/ModelSteps/Scan.jsx
- test/components/AppLike.jsx
The choice of a qualification in the Fab menu from a sub-category of papers does not launch the process of creation of a paper
> fix: Fab menu in sub category of paper

- package.json
- yarn.lock
Updated cc to fix an issue that prevented saving 2 files of the same name via Safari
> feat: Updated cozy-client

- src/constants/papersDefinitions.json
- src/locales/en.json
- src/locales/fr.json
Papers in the featured list must have steps
> fix: Hide 2 papers featured & wording

- src/components/ModelSteps/AcquisitionResult.jsx
- src/components/ModelSteps/Contact.jsx
- src/components/ModelSteps/Information.jsx
- src/components/ModelSteps/Scan.jsx
Let's make our designer happy and of course our users
> fix: 16px margin bottom for DialogAction

- src/components/CompositeHeader/CompositeHeader.jsx
- src/components/ModelSteps/Information.jsx
> Fix/next btn mobile#777

- src/targets/browser/index.jsx
- src/targets/browser/serviceWorkerRegistration.js
- src/targets/vendor/assets/service-worker.js
Added SW for manage PWA updates
> feat: Added service worker used by CRA

- src/components/Contexts/PapersDefinitionsProvider.jsx
- src/components/Hooks/usePapersDefinitions.jsx
- src/components/Papers/PaperLine.jsx
- src/components/Placeholders/Placeholder.jsx
- src/targets/browser/index.jsx
- test/components/AppLike.jsx
Simplified the use of the papers configuration and anticipate for the use of others configurations files (via flag)
> feat: Added PapersDefinitionsProvider

- src/components/Papers/PaperLine.jsx
- src/utils/getThumbnailLink.js
- src/utils/getThumbnailLink.spec.js
Adding a thumbnail, if it exists, on each line of paper
> feat: Added thumbnail

- src/components/ImportDropdown/ImportDropdown.jsx
- src/constants/papersDefinitions.json
Added of the name of the konnector to have the possibility of reaching it directly.
> feat: added connectorCriteria name

- src/components/App.jsx
- src/components/Contexts/PapersDefinitionsProvider.jsx
- src/components/HomeWrapper/HomeWrapper.jsx
- src/components/Papers/PaperGroup.jsx
- src/components/Placeholders/FeaturedPlaceholdersList.jsx
- src/components/Placeholders/FeaturedPlaceholdersList.spec.jsx
- src/components/Placeholders/PlaceholdersList.jsx
- src/helpers/findPlaceholders.js
- src/helpers/findPlaceholders.spec.js
- src/helpers/queries.js
- src/targets/browser/setupApp.jsx
- src/utils/fetchJsonFileByName.js
- src/utils/fetchJsonFileByName.spec.js
Added cozy-flag to add more flexibility to the "papersDefinitions.json" configuration file.
Now, with the correct flag, we can load this file from our Drive.
> feat: Added cozy-flags for manage configuration

- src/components/Papers/PaperLine.jsx
- src/utils/getThumbnailLink.js
Quick fixe, the real time does not give the same IOCozyFile object
The Links attribute is missing
> fix: Links attribute doesn't always exist

- src/components/Placeholders/PlaceholdersList.jsx
- src/constants/papersDefinitions.json
Fix possibility to access to menu dropdown in list of all placeholders
Added `placeholder.connectorCriteria` condition to enable bottom menu
> feat: Add connector link to all tax* choice

- src/components/Papers/PaperGroup.jsx
- src/helpers/queries.js
Revert `getPapersByLabel` changes
see: c3f652d
> feat: Sort list of categories

- src/components/App.jsx
- src/components/Papers/PapersList.jsx
- src/components/Papers/PapersList.spec.jsx
- src/components/Papers/PapersListByContact.jsx
- src/components/Papers/PapersListByContact.spec.jsx
- src/components/Papers/PapersListWrapper.jsx
- src/helpers/buildPaperslistByContact.js
- src/helpers/buildPaperslistByContact.spec.js
- src/locales/en.json
- src/locales/fr.json
Added a "See more" button if the number of Papers of a contact is greater than the `maxDisplay` parameter (see the configuration file).
On click, reveals all Papers of the current category of this contact.
> feat: Add maxDisplay limit for PapersList

- package.json
- yarn.lock
Update cozy-ui to 58.4.1 to get the BottomSheet fix ( cozy/cozy-ui@ddb8715 )
> feat: Update cozy-ui to 58.4.1

- src/constants/papersDefinitions.json
- src/helpers/buildFilename.js
- src/helpers/buildFilename.spec.js
- src/helpers/createPdfAndSave.js
- src/locales/en.json
- src/locales/fr.json
Added `filenameModel` & `labelGivenByUser` attributes for manage paper name when created
> feat: Add filenameModel attribute

- src/components/Papers/PaperGroup.jsx
Replace PDF icon by FileImageLoader in PaperGroup list
The image used is not necessarily that of the first file in the list
> feat: Add FileImageLoader to PaperGroup

- src/components/PapersFab/PapersFab.jsx
Move the PaperFab to prevent it from overlapping the Claudy Fab
> fix: Move PaperFab

- package.json
- src/components/Contexts/PapersDefinitionsProvider.jsx
- src/constants/papersDefinitions.json
- src/helpers/buildFilename.js
- src/helpers/buildFilename.spec.js
- src/helpers/buildPapersDefinitions.js
- src/helpers/buildPapersDefinitions.spec.js
- src/helpers/findPlaceholders.js
- src/locales/en.json
- src/locales/fr.json
- yarn.lock
Added Papers in `paperDefinitions.json` file, sort Papers in `PapersDefinitionsProvider` & fix `buildFilename`
> feat: Update paperDefinitions

- package.json
- src/targets/browser/index.jsx
- yarn.lock
Added `cozy-intent` to fix the BC in version 59 of cozy-ui (https://github.com/cozy/cozy-ui/releases/tag/v59.0.0)
> feat: Add cozy-intent package

- package.json
- yarn.lock
Add `cozy-device-helper` package to fix the crash when opening `ContactsListModal`.
In addition to 521de7b
> feat: Add cozy-device-helper

- package.json
- test/jestLib/setup.js
- yarn.lock
Unused and blocking for future updates of React
> feat: Remove enzyme package

- src/locales/en.json
- src/locales/fr.json
Changed the word "import" to "select" for less ambiguity.
> feat: Change wording

- src/components/ModelSteps/Contact.jsx
In Desktop mode the UX of the contact list when creating a paper was not compliant
> fix: Improve UX of Contact

- src/components/Placeholders/PlaceholderThemesList.jsx
- src/components/Placeholders/PlaceholdersList.jsx
Fix Proptypes on the components `PlaceholderThemesList` & PlaceholderList
> fix: Remove warning Proptypes

- CHANGELOG.md
- manifest.webapp
- package.json
Updated changelog from 0.1.0-beta.4 and new approach for future releases
See: https://github.com/cozy/cozy-libs/tree/master/packages/cozy-app-publish#release-workflow
> chore: Bump to 0.2.0

- src/components/AppRouter.jsx
- src/components/AppRouter.spec.jsx
- src/components/PapersFab/PapersFab.jsx
- src/components/Placeholders/FeaturedPlaceholdersList.jsx
- src/components/Placeholders/PlaceholdersList.jsx
The modals to create a paper were working but we had no content in the background.
I chose to use the query params to keep the information if the page is reloaded
> fix: Open modal with background content

- src/components/Placeholders/FeaturedPlaceholdersList.jsx
no changelog update, it was a regression
comme on est dans un tableau, il faut utiliser un tableau de référence, sinon on a toujours le dernier élément comme ref.
> fix: ActionMenuImportDropdown position in FeaturedPlaceholdersList

- .bundlemonrc
Relative https://github.com/cozy/mespapiers/pull/202#pullrequestreview-935057595
> chore: Update bundlemon config

- CHANGELOG.md
- package.json
- yarn.lock
To benefit from the latest fixes
> feat: Update cozy-mespapiers-lib to v0.5.11

- CHANGELOG.md
- manifest.webapp
relative to cozy-ui BC : https://github.com/cozy/cozy-ui/releases/tag/v64.0.0
> chore: Add `POST` permission on `io.cozy.contacts.*`

- CHANGELOG.md
- package.json
- yarn.lock
> feat: Update cozy-client to 32.2.0

- renovate.json
[chore(renovate): use feat prefix as scope of commit inside renovate PR](https://github.com/cozy/mespapiers/commit/0fc17afcbecd582e9270e005c572157fd22f671a)
[chore(renovate): bump version of cozy libraries and keep pinning depe…](https://github.com/cozy/mespapiers/commit/9fcbc7e445b551d60cc36df8c31a50cee84b32f0)
[chore(renovate): automerge activate for patch of cozy-lib](https://github.com/cozy/mespapiers/commit/b53239b59d78e9431247e0bc8e823d7ae55bc697)
Before merging this PR, the following things must have been done:
> chore(renovate): several optimisation for automerge strategy

- CODEOWNERS
limited because of https://github.com/organizations/cozy/settings/installations/27096946
> chore(renovate): remove CODEOWNERs to allow renovate automerge

- CHANGELOG.md
- manifest.webapp
- package.json
Version 2.0.0 never existed, the application goes from version 1.2.1 to 2.0.1
> chore: Bump to 2.0.1

- package.json
- yarn.lock
Fix wording of `driver_license` suggestion
```
* Update cozy-mespapiers-lib from [8.0.0](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%408.0.0) to [8.0.5](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%408.0.5)
```
> feat: Update cozy-mespapiers-lib from 8.0.0 to 8.0.5

- .bundlemonrc
- package.json
- yarn.lock
Not impacted by the BC
```
* Update cozy-mespapiers-lib from [8.0.5](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%408.0.5) to [9.1.0](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%409.1.0)
* Update cozy-ui from [75.6.1](https://github.com/cozy/cozy-ui/releases/tag/v75.6.1) to [77.2.0](https://github.com/cozy/cozy-ui/releases/tag/v77.2.0)
```
> feat: Update cozy-mespapiers-lib & cozy-ui

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from [10.0.0](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%4010.0.0) to [10.0.4](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%4010.0.4)
```
> feat: Update cozy-mespapiers-lib to

- package.json
- yarn.lock
```
* Upgrade cozy-mespapiers-lib 10.0.4 to 10.1.1
```
> feat: Upgrade cozy-mespapiers-lib 10.0.4 to 10.1.1

- src/locales/en.json
- src/locales/fr.json
- src/notifications/template.hbs
> Add two line breaks between sentences in the notification template

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from [11.0.4](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%4011.0.4) to [11.1.1](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%4011.1.1)
```
> feat(mespapiers): Update cozy-mespapiers-lib package to 11.1.1

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from 13.1.0 to 13.1.3
```
> feat: Update cozy-mespapiers-lib to 13.1.3

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from 14.0.0 to 14.0.1
```
> feat: Update cozy-mespapiers-lib to 14.0.1

- src/notifications/index.js
```
* Link to redirect the papers contained in the email
```
> fix: Link to redirect the papers contained in the email

- src/components/AppProviders.jsx
- src/components/AppProviders.spec.jsx
```
* Remove call to mui/core and use cozy-ui instead
```
> feat: Remove call to mui/core

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from 15.1.0 to 15.2.0
```
> feat: Update cozy-mespapiers-lib from 15.1.0 to 15.2.0

- .github/workflows/update_libs.yml
- .gitignore
- package.json
- scripts/update_libs.js
- scripts/utils.js
- scripts/utils.spec.js
- yarn.lock
```
* Add GH actions to compare the peerDeps of the chosen libs with the deps of the app, to update them if necessary and finally create the PR.
```
> chore: Add GH actions

- .github/auto-merge.yml
```
* Add auto-merge config
```
> chore: Add auto merge config

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from ^36.0.1 to ^36.1.0
```
> feat: Update cozy-mespapiers-lib from 36.0.1 to 36.1.0

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from 36.1.0 to 36.1.6
```
> Update dep for 2.0.4

- scripts/utils.js
```
* Display full version of the previous package
```
> chore: Display full version of the previous package

- package.json
- src/components/App.jsx
- yarn.lock
```
* Limit width of application on Desktop mode (1200px)
```
> feat: Limit width of application on Desktop mode

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from `39.0.0` to `39.0.1`
* Update devDep cozy-bar from `7.25.0` to `7.26.0`
```
> feat: Update cozy-mespapiers-lib from `39.0.0` to `39.0.1`

- package.json
- yarn.lock
```
* Update cozy-flags from `2.11.0` to `3.0.1`
```
-  [x] Wait https://github.com/cozy/cozy-bar/pull/824
> feat: Update cozy-flags from `2.11.0` to `3.0.1`

- src/locales/en.json
- src/locales/fr.json
```
* Change help modal wording
```
> feat: Change help modal wording

- src/locales/en.json
- src/locales/fr.json
```
* Change help modal wording
```
> backport Change help modal wording

- src/locales/en.json
- src/locales/fr.json
changement fait sur la branche 2.2.1 qu'on reporte ici
```
* Change help modal wording
```
> change wording

- package.json
- src/targets/browser/setupApp.jsx
- yarn.lock
> feat: Add sentry

- manifest.webapp
replace appname Mes papiers by Mes Papiers
```
* replace appname Mes papiers by Mes Papiers
```
> feat: Rename appname in manifest

- package.json
- src/helpers/client.js
```
* Add intents compliancy and cozy-interapp 0.8.0
```
> feat: Add intents compliancy

- package.json
- yarn.lock
```
* Update cozy-client from `38.11.1` to `40.0.1`
```
> feat: Update cozy-client to `40.0.1`

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from ^60.0.0 to ^60.0.4
```
> feat: Update cozy-mespapiers-lib from `60.0.0` to `60.0.4`

- package.json
- yarn.lock
* Handle incoming files from cozy-flagship for upload
> feat: Update mespapiers-lib from 61.3.0 to 61.4.0

- app.config.js
- package.json
- src/targets/browser/setupApp.jsx
- yarn.lock
```
* use CozyDevTools instead FlagSwitcher
```
> Chore: use CozyDevTools instead FlagSwitcher

- .travis.yml
```
* Bump to node 20
* Remove travis caches
```
> Chore: Remove travis caches & Bump to node 20

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib to 70.0.6
```
> feat: Update cozy-mespapiers-lib to 70.0.6

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from 72.0.1 to 72.2.0
```
> feat: Update cozy-mespapiers-lib to 72.2.0

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from 72.2.0 to 72.3.0
```
> feat: Update cozy-mespapiers-lib to 72.3.0

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from  73.0.1 to 73.1.1
```
> feat: Update cozy-mespapiers-lib

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from  73.1.1 to 73.2.0
```
> feat: Update cozy-mespapiers-lib to 73.2.0

- package.json
- yarn.lock
```
* Upgrade cozy-mespapiers-lib 75.0.0 to 75.2.0
```
> feat: Upgrade cozy-mespapiers-lib 75.0.0 to 75.2.0

- package.json
- yarn.lock
```
* Upgrade cozy-mespapiers-lib 75.2.0 to 75.4.0
```
> feat: Upgrade cozy-mespapiers-lib 75.2.0 to 75.4.0

- package.json
- yarn.lock
```
* Upgrade cozy-mespapiers-lib 75.4.0 to 75.6.2
```
> feat: Upgrade cozy-mespapiers-lib 75.4.0 to 75.6.2

- package.json
- yarn.lock
```
* Upgrade cozy-mespapiers-lib to 78.0.0
```
> feat: Upgrade cozy-mespapiers-lib to 78.0.0

- package.json
- yarn.lock
```
* Upgrade cozy-mespapiers-lib 78.2.0 to 78.2.2
```
> feat: Upgrade cozy-mespapiers-lib 78.2.0 to 78.2.2

- package.json
- src/components/App.jsx
- src/components/AppProviders.jsx
- src/components/AppProviders.spec.jsx
- src/components/Help.jsx
- src/helpers/bar.js
- src/helpers/client.js
- src/targets/browser/index.ejs
- src/targets/browser/index.jsx
- src/targets/browser/setupApp.jsx
- test/jestLib/setup.js
- yarn.lock
Should upgrade cozy-mespapiers-lib first
```
* Upgrade cozy-bar v7 to v11
```
> feat: Add cozy-bar v11

- package.json
- yarn.lock
```
* Upgrade cozy-mespapiers-lib to 88.0.3
```
> feat: Upgrade cozy-mespapiers-lib to 88.0.3

- package.json
- yarn.lock
```
* Upgrade cozy-mespapiers-lib to 88.0.5
```
> feat: Upgrade cozy-mespapiers-lib to 88.0.5

- src/helpers/migration/metadata.js
We have this metadata on tax documents
```
* Add `taxNumber` to migration script
```
> feat: Add `taxNumber` to migration script

- package.json
- yarn.lock
* Hide shared drives dir in filepicker
> feat: Update cozy-ui to 105.9.0

- CHANGELOG.md
- manifest.webapp
- package.json
> chore: Bump to 3.4.0

- manifest.webapp
- src/locales/en.json
- src/locales/fr.json
- src/notifications/index.js
```
* [Change the execution time slot for the expiration service](https://github.com/cozy/mespapiers/commit/4f8f95cc207d115c985bb35538176f4009c4c631)
* [Add mobile notifications to the expiration service](https://github.com/cozy/mespapiers/commit/6198fd9b033dc8b5d1a194645079967ad2158436)
```
> feat: Add mobile notifications to the expiration service

- src/components/AppLayout.jsx
- src/components/AppRouter.jsx
- src/components/Fabs.jsx
Specifically on Desktop.
As one of the first components loaded, the position calculation is not correct. Positioning it in AppLayout fix the problem,
and it makes more sense to put it here than in the routes.
> fix: AppFabs component does not appear

- package.json
- src/components/Actions/Items/forwardTo.jsx
- yarn.lock
```
* Fix forwarding multiple files
```
> Fix forwarding multiple files

- src/components/Actions/Items/copyReminderContent.jsx
- src/components/Actions/Items/createPaper.jsx
- src/components/Actions/Items/createPaperByQualificationLabel.jsx
- src/components/Actions/Items/download.jsx
- src/components/Actions/Items/editContact.jsx
- src/components/Actions/Items/forward.jsx
- src/components/Actions/Items/importAuto.jsx
- src/components/Actions/Items/open.jsx
- src/components/Actions/Items/rename.jsx
- src/components/Actions/Items/scanPicture.jsx
- src/components/Actions/Items/select.jsx
- src/components/Actions/Items/trash.jsx
- src/components/Actions/Items/viewInDrive.jsx
- src/components/AppRouter.jsx
- src/components/Harvest/CannotConnectModal/ExtraContent.jsx
- src/components/ModelSteps/widgets/CountryListAdapter.jsx
- src/helpers/combinePaths.js
- src/helpers/combinePaths.spec.js
- src/locales/en.json
- src/locales/fr.json
- src/locales/withLocales.js
```
* Do not display all nationalities when creating certain papers.
```
> feat: Do not display all nationalities

- src/components/ModelSteps/widgets/CountryListAdapter.jsx
- src/locales/en.json
- src/locales/fr.json
- src/papersDefinitions.json
```
* Change country name for foreign papers
* Use isp instead of telecom for konnectors
* Typo on OCR info dialog
```
> Change country logic

- package.json
- src/locales/fr.json
- yarn.lock
```
*  Update french wording of the vehicle registration license number [5f0029f](https://github.com/cozy/mespapiers/commit/5f0029f7585776a430dfc2a7bd1f9681c19c8986)
* Upgrade cozy-client from `48.3.0` to `48.4.0`
```
> feat: Update french wording of the vehicle registration license number

- src/components/AppProviders.jsx
- src/components/AppRouter.jsx
- src/components/Contexts/CreatePaperDataBackupProvider.jsx
- src/targets/browser/index.jsx
```
* Reorganize providers to put them all at the same place
```
> refactor: Reorganize providers to put them all at the same place

- src/components/Actions/Items/modify.jsx
- src/components/ModelSteps/widgets/SubmitButton.jsx
- src/components/ModelSteps/widgets/helpers.js
- src/components/Views/Edit.jsx
- src/components/Views/helpers.js
- src/helpers/getPdfPage.js
Corrections and adjustments to the paper modification feature.
See commits messages.
> fix: Edit paper feature

- src/components/Multiselect/ForwardModal.jsx
- src/components/Multiselect/LinearBackdrop.jsx
- src/locales/en.json
- src/locales/fr.json
> feat(ForwardModal): Asynchronous processing before share validation

- src/components/ModelSteps/Scan/EncryptedPDFModal.jsx
- src/components/ModelSteps/Scan/ScanWrapper.jsx
- src/locales/en.json
- src/locales/fr.json
```
* Show message if imported pdf is encrypted
```
> feat: Show message if imported pdf is encrypted

- src/components/ModelSteps/Edit/helpers.js
- src/components/ModelSteps/Edit/helpers.spec.js
```
* Paper model was incorrect for french driver license
```
> Paper model was incorrect for french driver license

- package.json
- src/components/Search/helpers.js
- src/components/Search/search.js
- src/locales/en.json
- src/locales/fr.json
- yarn.lock
```
* Rename "numéro de la carte vitale" in "sécurité sociale"
```
> Rename "numéro de la carte vitale" in "sécurité sociale"

- src/papersDefinitions.json
- src/papersDefinitions_health.json
```
*  Change icons for some qualification
```
> feat: Change icons for some qualification

- package.json
- src/helpers/createPdfAndSave.js
- src/helpers/createPdfAndSave.spec.js
- yarn.lock
```
* Don't create a new pdf if the selected paper is already one
```
> Don't create a new pdf if the selected paper is already one

- src/components/ModelSteps/Scan/ScanActions/ScanDesktopActions.spec.jsx
- src/components/ModelSteps/Scan/ScanActions/ScanDesktopActionsAlert.spec.jsx
- src/locales/en.json
- src/locales/fr.json
```
* Change wording for ScanDesktopActionsAlert
```
> feat: Change wording for ScanDesktopActionsAlert

- .github/workflows/ci-cd.yml
> chore: Add Bundlemon GA

- package.json
- yarn.lock
```
* Update cozy-client from 48.25.0 to 49.8.0
* Update cozy-intent from 2.21.0 to 2.23.2
```
> feat: Update packages

- src/targets/intents/index.jsx
Forgot to migrate to React 18
cf https://github.com/cozy/mespapiers/pull/682
> feat: Intents target must be migrate too
