cozy/mespapiers

- src/components/DialogInStepper/DialogInStepper.jsx
- src/components/DialogInStepper/index.jsx
- src/components/DialogInStepper/styles.styl
- src/styles/index.styl
Nous devons implémenter une modale type `CozyDialog`, mais dans le contexte d'un Stepper.
Nous avons besoin de lui passer un composant ayant son contenu et ses actions plutôt que de devoir séparer les deux.
Le contenu étant dynamique, nous ne pouvons pas avoir des actions séparées, ces dernières seront à chaque step dépendantes du contenu.
> feat: Add DialogInStepper component

- src/components/Contexts/StepperDialogProvider.jsx
- src/components/Placeholders/Placeholder.jsx
- src/components/StepperDialogWrapper/StepperDialogWrapper.jsx
- src/constants/papersDefinitions.json
- src/utils/getPlaceholders.js
- src/utils/getPlaceholders.spec.js
Mise à jour du fichier JSON `paperDefinition` et des fichiers qui l'utilisent.
La modification majeur permet d'ajouter dynamiquement des pages dans le parcours si l'occurrence de celle-ci est supérieur à 1.
Ajout également de la prise en compte de l'ordre de la liste des placeholders
> feat: Update papers definitions

- src/components/CompositeHeader/CompositeHeader.jsx
- src/components/CompositeHeader/styles.styl
Mise à jour du composant `CompositeHeader` :
- Ajout de la prop `IconSize` pour gérer la taille de l'icône
- Ajout de la possibilité de passer des composants aux props `title` & `text`
> feat: Upgrade CompositeHeader component

- src/components/Contexts/FormDataProvider.jsx
- src/components/ModelSteps/AcquisitionResult.jsx
- src/components/ModelSteps/Information.jsx
- src/components/ModelSteps/widgets/InputDateAdapter.jsx
- src/components/ModelSteps/widgets/InputTextAdapter.jsx
- src/constants/papersDefinitions.json
- src/locales/en.json
- src/locales/fr.json
Refacto du state `formData` pour convenir au nouveau besoin.
Ex: En fin de process, nous voulons pouvoir enregistrer chaque fichier avec leur propre `fileMetadata` (`page` & `pageName`), les `metadata` générales et le `contact`
> feat: Rework formData

- src/components/Contexts/StepperDialogProvider.jsx
- src/components/ModelSteps/Information.jsx
- src/components/Placeholders/PaperDefinitionsPropTypes.js
- src/components/Placeholders/Placeholder.jsx
- src/constants/papersDefinitions.json
- src/utils/getPlaceholders.js
- src/utils/getPlaceholders.spec.js
PapersDefinition added:
- Added `multipage` prop in `acquisitionSteps`
- Replace `birth_certificate` to `health_certificate`
- Added `id_photo`
- Added steps of `pay_sheet`
- Added steps of `tax_notice`
Refactoring:
- Renamed `steps` to `acquisitionSteps`
- Renamed `Numbers12Digits` & `frenchIdCardNumber` value to `Number:12`
- Removed `featuredPlaceholder` which has become useless
> feat: Add PapersDefinition & refactor

- src/components/ModelSteps/AcquisitionResult.jsx
- src/components/Placeholders/Placeholder.jsx
- src/constants/PaperDefinitionsPropTypes.js
- src/locales/en.json
- src/locales/fr.json
Change `occurrence` attribute to `multipage` in `acquisitionSteps`
The `occurence` attribute was never built into the code, it should have done what `multipage` does now.
A Paper does not necessarily have a defined number of pages, this attribute allows the user to load as many files as needed.
> feat: Change occurrence attribute to multipage

- src/constants/papersDefinitions.json
- Removal of health_certificate steps that are not ready.
- `health_certificate` & `tax_timetable` are no longer proposed on the homepage.
> feat: Updtate papersDefinitions

- src/components/Contexts/FormDataProvider.jsx
As the form allows user to import any image we want to limit the image
dimensions in the generated PDF
The image is resized regarding its longest side
Current size limitation is `900px` wide. This is a randomly chosen number, so let's discuss about which dimension we want as a max image size.
> feat: Limit image size in pdf

- src/helpers/queries.js
In the app, two requests are executed.
The first request only retrieves the qualifications' labels and then the second one requests all qualifications's data.
If this second request is made before the first one expired (as defined by fetchPolicy), then returned data will be incorrect (only labels are returned instead of all data)
> fix: Filename is displayed instead of the pageName

- src/components/ModelSteps/Information.jsx
Added debounce to avoid a double call, which could validate the next step.
> fix: Added debounce on information submit

- package.json
- src/components/Contexts/ScannerI18nProvider.jsx
- src/components/ImportDropdown/ImportDropdown.spec.jsx
- src/components/ModelSteps/widgets/InputTextAdapter.spec.jsx
- src/components/Papers/PaperLine.spec.jsx
- src/components/Placeholders/FeaturedPlaceholdersList.spec.jsx
- src/components/Placeholders/Placeholder.spec.jsx
- src/components/Placeholders/PlaceholderThemesList.jsx
- src/components/Placeholders/PlaceholdersList.spec.jsx
- src/components/Viewer/Panel/Qualification.jsx
- test/components/AppLike.jsx
- yarn.lock
From version 27.3.1 of cozy-client, we can do without cozy-scanner for themes and translations of qualifications
> Refactor: Using cozy-client instead cozy-scanner

- src/components/Contexts/FormDataProvider.jsx
- src/components/Papers/PaperLine.jsx
- src/components/Viewer/Panel/Qualification.jsx
The attributes that are not qualification attributes should be removed from the `qualification:` object, but remain in the `metadata`
> feat: Move metadata

- src/components/ModelSteps/widgets/InputDateAdapter.jsx
If a date is selected or entered manually and then deleted, the value becomes `Invalid Date`.
It is better in this case to replace this value with `null`.
> fix: Incorrect date value

- src/components/ModelSteps/Information.jsx
- src/components/ModelSteps/widgets/InputDateAdapter.jsx
- src/components/ModelSteps/widgets/InputTextAdapter.jsx
- src/components/ModelSteps/widgets/InputTextAdapter.spec.jsx
- src/constants/papersDefinitions.json
- src/utils/input.js
- src/utils/input.spec.js
For a better maintainability, the definition of Inputs in the configuration file should follow the official API for inputs
(At least for the constraint rules)
> refactor: Management of the InputText constraints

- src/components/Home/Home.jsx
When we have more than 100 papers (maximum limit), we need `fetchMorePapers` to get the rest.
We need to fetch all the papers for the construction of the Home.
> fix: Add fetchMore function for load all papers

- src/components/ModelSteps/AcquisitionResult.jsx
- src/components/ModelSteps/Contact.jsx
- src/components/ModelSteps/Scan.jsx
- src/components/ModelSteps/widgets/ConfirmReplaceFile.jsx
- src/helpers/makeBlobWithCustomAttrs.js
- src/helpers/makeBlobWithCustomAttrs.spec.js
- src/locales/en.json
- src/locales/fr.json
At the end of the process of creating a Paper, if at least one file has been chosen from the Drive, a confirmation modal appears to give the user the choice to replace the original files
> feat: Add a confirm modal

- src/components/ModelSteps/ScanDesktopActions.jsx
- src/components/ModelSteps/ScanMobileActions.jsx
Following the PR #176, the prop `icon` on the Buttons has changed for `startIcon` which takes a component `Icon`.
> fix: Change prop Icon by startIcon on new Buttons

- src/components/ImportDropdown/ImportDropdown.jsx
On aurait pu faire la modification dans cozy-ui mais :
- besoin présent que dans cette app
- plus rapide à faire ici
- l'actionMenu de cozy-ui n'est de toute façon pas conforme aux specs figma, un chantier est prévu, qui embarquera cette possibilité de disable
Du fait qu'on manque de temps, et qu'on ne fait que rajouter des classes, il n'y a pas de test (la philosophie de testing lib n'étant pas trop de tester la présence de classe css si je dis pas de bêtise)
> feat: Add disabled effect on ImportDropdown

- package.json
- yarn.lock
This PR will open Store with openApp instead of inApp browser if webviewintent is available
> feat: Use openApp() when importing files in Amiral instead of blank href inApp browser

- renovate.json
and keep using "Dependency Dashboard" on every deps except cozy-*.
since renovate@26.0.0, the "Dependency Dashboard" is listing issues to upgrade, instead of opening PRs.
For Cozy libraries, we want the creation of PR immediately.
> chore(deps): Configure renovate to open PR directly on cozy libraries

- CHANGELOG.md
- package.json
- src/components/App.jsx
- yarn.lock
L'implémentation du composant PaperFab à changé sur la version [0.44.0](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%400.44.0).
Il n'est plus exporté et est utilisé par défaut dans la lib.
> Feat/update cozy mespapiers lib to 1.1.0

- CHANGELOG.md
- manifest.webapp
- package.json
Bump to version 1.2.0 to synchronize with another application
> chore: Bump from 0.6.0 to 1.2.0

- package.json
- yarn.lock
Mise à jour des libs cozy-mespapiers-lib, cozy-ui & cozy-client afin de bénéficier du permis étranger et français ainsi que de la carte nationale d'identité française
```
* Update cozy-mespapiers-lib from [4.0.0](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%404.0.0) to [5.0.1](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%405.0.1)
* Update cozy-ui from [75.0.0](https://github.com/cozy/cozy-ui/releases/tag/v75.0.0) to [75.3.0](https://github.com/cozy/cozy-ui/releases/tag/v75.3.0)
* Update cozy-client from [33.0.6](https://github.com/cozy/cozy-client/releases/tag/v33.0.6) to [33.1.0](https://github.com/cozy/cozy-client/releases/tag/v33.1.0)
```
> Update cozy mespapiers lib to 5.0.1

- package.json
- yarn.lock
Mise à jour des libs cozy-mespapiers-lib & cozy-ui pour bénéficier des fix apportés au Viewer
- Affichage des titulaires
- Modification du pays sur un papier "étranger"
- Ne pas afficher le menu de modification pour la metadata issueDate d'un fichier si ce dernier provient d'un Connecteur
```
* Update cozy-mespapiers-lib from [6.0.0](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%406.0.0) to [7.0.0](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%407.0.0)
* Update cozy-ui from [75.4.0](https://github.com/cozy/cozy-ui/releases/tag/v75.4.0) to [75.6.0](https://github.com/cozy/cozy-ui/releases/tag/v75.6.0)
```
> Update cozy cozy-mespapiers-lib to 7.0.0 & cozy-ui to 75.6.0

- package.json
- yarn.lock
Not impacted by the BC
```
* Update cozy-mespapiers-lib from [8.0.5](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%408.0.5) to [9.0.3](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%409.0.3)
```
> feat: Update cozy-mespapiers-lib to 9.0.3

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from [9.1.0](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%409.1.0) to [9.2.0](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%409.2.0)
```
> feat: Update cozy-mespapiers-lib to 9.2.0

- .bundlemonrc
- README.md
- package.json
- src/constants.js
- src/doctypes/index.js
- src/helpers/queries.js
- src/helpers/service.js
- src/helpers/service.spec.js
- src/targets/services/expiration.js
- src/targets/services/launchTriggers.js
- yarn.lock
Cette PR se contente d'implémenter le service qui doit retourner les fichiers(papiers) qui vont expirer.
- Carte d'identité FR
- Titres de séjours
On se base sur la date d'expiration(expirationDate) - 90 jours (90 est la valeur par défaut, l'utilisateur aura le choix lors de la création ou édition du papier)
- Licence sportive
Dans ce cas, on se base sur la date de référence(referencedDate) + 365, avec un délai de prévenance de - 15 jours. 
Si la date de référence n'est pas renseigné, on se base alors sur la date de création(created_at) du fichier.
```
* Add expiration service
```
> Create expiration service

- package.json
- yarn.lock
BC is to update cozy-client 33.1.0 to 34.2.0
no cozy-client BC to deal with
```
* Update cozy-mespapiers-lib 9.5.1 to 10.0.0
* Update cozy-client 33.1.0 to 34.2.0
```
> feat: Update cozy-mespapiers-lib 9.5.1 to 10.0.0

- app.config.js
- package.json
- src/constants.js
- src/helpers/service.js
- src/helpers/service.spec.js
- src/locales/en.json
- src/locales/fr.json
- src/notifications/helpers.js
- src/notifications/index.js
- src/notifications/template.hbs
- src/targets/services/expiration.js
- yarn.lock
Cette PR ajoute tout le code nécessaire pour l'envoi d'un email lorsque des fichiers arrivent bientôt à expiration (délai de prévenance).
Après merge de https://github.com/cozy/cozy-client/pull/1274 et https://github.com/cozy/mespapiers/pull/330 nous pourrons mettre à jour le fichier le manifest pour activer le service en /dev
```
* Add email notification when files are about to expire.
* Add configuration for email notifications
```
> Email notification of files that are about to expire

- src/notifications/index.js
```
* Display filename without extension in the notification email
* Get the subDomain from the client instance
```
> Fix email wording

- package.json
- src/constants.js
- src/helpers/service.js
- src/helpers/service.spec.js
- yarn.lock
~~This is the last PR of the series that aims to add expiration information to the viewer and paper items.~~
This will be on top of https://github.com/cozy/cozy-client/pull/1274 and thus will need an update of `cozy-client`.
This does not include the work made in https://github.com/cozy/cozy-ui/pull/2294 and https://github.com/cozy/cozy-libs/pull/1894 that will also require an update of `cozy-ui` and `cozy-mespapiers-lib`.
```
* Update cozy-client from [34.2.0](https://github.com/cozy/cozy-client/releases/tag/v34.2.0) to [34.4.0](https://github.com/cozy/cozy-client/releases/tag/v34.4.0)
```
> Put expiration service on top of cozy client helpers

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from [10.1.1](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%4010.1.1) to [10.3.1](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%4010.3.1)
```
> feat: Update cozy-mespapiers-lib to 10.3.1

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from [11.0.0](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%4011.0.0) to [11.0.4](https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%4011.0.4)
* Update cozy-ui from [78.0.0](https://github.com/cozy/cozy-ui/releases/tag/v78.0.0) to [78.1.1](https://github.com/cozy/cozy-ui/releases/tag/v78.1.1)
```
> Update `cozy-ui` to 78.1.1 and `cozy-mespapiers-lib` to 11.0.4

- src/components/App.jsx
The layout route doesn't have a path attribute
See: https://reactrouter.com/en/main/start/concepts#pathless-routes
(Except if the child route is indexed on it)
> fix: Remove layout path

- src/locales/en.json
- src/locales/fr.json
- src/notifications/index.js
```
* Add the subject of the expiration notification email
```
Il s'avère que la méthode `getTitle` est aussi utile pour les notification par email, c'est elle qui définie l'objet du mail.
> feat: Add the subject of the expiration notification email

- src/helpers/migration/metadata.js
- src/helpers/migration/metadata.spec.js
- src/targets/services/metadataMigration.js
- tsconfig.json
```
* The query used to fetch files can return files without the `metadata` attribute, we need to make sure we only have files with the `metadata` attribute
```
> Fix: service metadata migration

- src/helpers/migration/metadata.js
- src/helpers/migration/metadata.spec.js
```
* The migration script could encounter an error when trying to access certain properties, if the doctype `io.cozy.mypapers.settings` did not exist.
```
> fix: Update app settings if it doesn't exist

- src/targets/services/metadataMigration.js
```
* Change log `warn` to `info` if no file with metadata found
```
> fix: Change log `warn` to `info` if no file with metadata found

- src/components/App.jsx
- src/components/Help.jsx
- src/locales/en.json
- src/locales/fr.json
Grâce au flag `mespapiers.show-help.enabled` on souhaite pouvoir afficher un bouton d'aide dans la cozy-bar, afin de faire poper une modale informative concernant l'application
```
* Add help modal and button
```
> Add help button behind flag

- package.json
- yarn.lock
```
* Update cozy-mespapiers-lib from ^46.0.4 to ^46.1.0
* Add expiration date and delay on stranger driver license.
* Refactor of Steppers Dialog to use Cozy Dialog instead.
* Change Passport & driver license illustrations
```
> feat: Update cozy-mespapiers-lib from `46.0.4` to `46.2.0`

- package.json
- yarn.lock
Backport https://github.com/cozy/mespapiers/pull/468
> feat: Update cozy-mespapiers-lib from `46.2.0` to `46.3.0`

- package.json
- yarn.lock
This update change the translation of bank_details from IBAN to RIB
```
* Update cozy-client from 40.3.0 to 40.6.0
```
> feat: Update cozy-client from 40.3.0 to 40.6.0

- package.json
- yarn.lock
This will ignore onboarding guard when uploading from flagship
> feat: Update mespapiers-lib from 61.4.0 to 61.5.0

- .travis.yml
```
* Travis executes the yarn test command by default when we specify multiple node versions at the root.
In this case we run the tests twice.
```
> chore: Refactor Travis CI stage

- .stylintrc
- src/styles/index.styl
Ceci est un correctif rapide temporaire le temps de corriger le problème de fond.
En réalité le souci est un conflit de css entre la dernière version de cozy-ui et une autre version. Cette version est injecté par la sous-dépendance cozy-sharing. En effet dans son css, il fait des imports directs de stylus de cozy-ui, ce qui n'est plus censé être fait. Et en l’occurrence, il importe button.styl de cozy-ui qui lui-même dans cozy-ui importe text.styl à l'intérieur duquel il y a la création des classes utilitaires.
De plus, il y a la cozy-bar v7 qui vient avec son style cozy-ui propre qui pose également problème.
Pour corriger le souci correctement il faut donc : 
- corriger cozy-ui pour éviter la double création des classes utilitaires
- mettre à jour cozy-ui dans cozy-sharing et mettre …
> feat: Override u.midellipsis style

- src/constants.js
- src/notifications/helpers.js
```
* The expiration service crashes if the Cozy language is not supported by the application.
```
> fix: ExpirationNotification should use the "en" locale by default

- package.json
- yarn.lock
To get the use of sourceAccountIdentifier in harvest cards used in mespapiers
```
* mespapiers: Use showAlert instead Alerter into PapersDefinitions
* Update KonnectorBlock to use sourceAccountIdentifier
* Use sourceAccountIdentifier in files datacard
* Avoid losing cozy-client cache after reload
* datacard : request files with sourceAccountIdentifier and slug
* Deep clone account
```
> [SCR-167] feat: Upgrade cozy-harvest-lib to 22.5.4

- app.config.js
When merging the cozy-mespapiers-lib into the app, this configuration should have been added.
> fix: Add css-modules webpack configuration

- src/components/AppProviders.jsx
- src/components/AppRouter.jsx
- src/components/Contexts/CreatePaperDataBackupProvider.jsx
This change brings back a number of advantages, such as error handling (`errorElement` prop):
https://reactrouter.com/en/main/routers/picking-a-router#data-apis
And change `CreatePaperDataBackupRoute` to `CreatePaperDataBackupProvider`, for more sense and less router overload
> feat: Use data API router of react-router-dom

- src/helpers/createPdfAndSave.js
- src/helpers/createPdfAndSave.spec.js
- src/queries/index.js
```
* Use contants instead of strings to list all known metadata [6c0cec8](https://github.com/cozy/mespapiers/commit/6c0cec81791758c40f86225951d1315bfcc2d1bb)
* Cannot create papers without metadata [6947bcf](https://github.com/cozy/mespapiers/commit/6947bcf853ba241b6d560d61cdb0baac92d763d0)
```
> fix: Use contants instead of strings to list all known metadata

- src/helpers/migration/metadata.js
- src/targets/services/metadataMigration.js
In the case of first-time users, some functions need this document to work properly, so we need to make sure it exists.
We've had this regression since the removal of the onboarding screen, which took care of this among other things.(cozy/cozy-libs@a5e7d28)
To clarify, each time the app is loaded (new or reloaded), the `metadataMigration` job is created  if never created during the day.
This job ends up updating the document(creating it if it doesn't exist), but as the jobs are not synchronous, the problem of the missing document exists.
```
* Ensure the app settings document exists when the app is loaded
```
> feat: Ensure the app settings document exists when the app is loaded

- src/components/ModelSteps/NoteDialog.jsx
Following this commit a4ca8c1, the request always returns the `io.cozy.files` in an array.
The modification of this return has been forgotten here.
All these uses are now corrected.
> fix(NoteDialog): Note creation returns a 404 when trying to save

- package.json
- src/components/ModelSteps/ScanResult/OcrProcessingDialog.jsx
- src/components/ModelSteps/ScanResult/ScanResultDialog.spec.jsx
- yarn.lock
Following the modification to handle "deep" metadata (5ae2469).
```
* Set OCR metadata in the right place
* Upgrade cozy-ui from `110.5.0` to `110.7.0`
```
> fix(OCR): Set metadata in the correct place

- src/components/ModelSteps/Scan/ScanWrapper.jsx
- src/components/ModelSteps/widgets/SubmitButton.jsx
- src/components/ModelSteps/widgets/SubmitButton.spec.jsx
We also retrieve the original file name, to display something consistent.
```
* Save a new paper from the Cozy filePicker
```
> fix: Save a new paper from the Cozy filePicker

- src/components/Views/InformationEdit.jsx
If it is displayed directly when the page is loaded, the parent modal (Viewer), being async,
appears after and therefore above of it.
> fix: Style of InformationEdit Dialog

- .github/workflows/ci-cd.yml
- package.json
- yarn.lock
The variables `BUNDLEMON_PROJECT_ID` and `BUNDLEMON_PROJECT_APIKEY` are no longer required and must be deleted for new Bundlemon versions to work properly.
```
* Upgrade Bundlemon to 3.1.0
```
> chore: Upgrade Bundlemon to 3.1.0

- src/components/Multiselect/ForwardBottomSheet.jsx
When sharing as an attachment, only files created for sharing should be deleted.
As a reminder, files are created for sharing when the user wishes to share only one side of a document.
> fix: Do not remove all shared files

- src/components/Viewer/FilesViewer.jsx
- src/components/Views/InformationEdit.jsx
We had recently encountered the same z-index problem, but the correction brought this regression.
A more global fix for cozy-viewer may be in order in the future.
See: https://github.com/cozy/cozy-libs/issues/2595
> fix: Always keep the Viewer modal behind the others

- src/components/Multiselect/ForwardBottomSheet.jsx
```
*
* Fix infinite load when sharing on Android
*
```
> fix: Infinite load when sharing on Android

- docs/papersDefinitions.md
- package.json
- src/components/ModelSteps/Edit/helpers.js
- src/components/ModelSteps/Edit/helpers.spec.js
- src/helpers/filterSteps.js
- src/papersDefinitions.json
- yarn.lock
Nous avons introduit un bug avec la PR https://github.com/cozy/mespapiers/pull/681 . Initialement ... (à venir)
> Country metadata qualification wasn't correctly editable

- src/targets/intents/index.ejs
and so the wrong color scheme was applied in dark mode, resulting to white background instead of transparent.
For information, here's an interesting article https://fvsch.com/transparent-iframes
> fix: Color scheme was missing in for intents
